services:
  postgres:
    image: postgres:17
    container_name: medcore-postgres
    environment:
      POSTGRES_DB: medcore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - medcore_postgres_data:/var/lib/postgresql/data

volumes:
  medcore_postgres_data: