services:
  postgres:
    image: postgres:17
    container_name: patient-management-postgres
    environment:
      POSTGRES_DB: patient_management_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - patient_management_postgres_data:/var/lib/postgresql/data

volumes:
  patient_management_postgres_data: